version: '3'
services:
        dbos:
                container_name: mysql
                image: mysql:5.7
                volumes:
                        - mysql_storage:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: yash
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: drupal
                restart: always
        
        

        drupalos:
                container_name: drupal
                image: drupal:latest
                volumes:
                        - drupal_themes:/var/www/html/themes
                        - drupal_sites:/var/www/html/sites
                        - drupal_profiles:/var/www/html/profiles
                        - drupal_modules:/var/www/html/modules
                restart: always 
                ports:
                        - 1912:80

volumes:
       drupal_themes:
       drupal_modules:    
       drupal_profiles:
       drupal_sites:
       mysql_storage:                
